// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Options are what the generator makes; Kind picks which of the other fields apply.
 */
export interface Options {
    "kind": string;

    /**
     * Length, the character sets, the minimums and AvoidAmbiguous shape a password.
     */
    "length": number;
    "uppercase": boolean;
    "lowercase": boolean;
    "numbers": boolean;
    "symbols": boolean;
    "minNumbers": number;
    "minSymbols": number;
    "avoidAmbiguous": boolean;

    /**
     * Words, Separator, Capitalize and IncludeNumber shape a passphrase.
     */
    "words": number;
    "separator": string;
    "capitalize": boolean;
    "includeNumber": boolean;
}
