// Package resources renders the Android app's string resources from its JSON string source.
package resources

import (
	"bytes"
	"encoding/json"
	"encoding/xml"
	"fmt"
	"maps"
	"regexp"
	"slices"
	"strings"
)

// source is the language every string needs, and the one Android falls back to.
const source = "en"

var (
	namePattern     = regexp.MustCompile(`^[a-z][a-z0-9_]*$`)
	languagePattern = regexp.MustCompile(`^[a-z]{2}$`)
	// formatPattern matches the positional format specifiers a string takes.
	formatPattern = regexp.MustCompile(`%[0-9]+\$[a-z]`)
)

// Catalog is each string's text by language.
type Catalog map[string]map[string]string

// Parse reads a string source, rejecting any string whose languages or format specifiers differ from English.
func Parse(data []byte) (Catalog, error) {
	var catalog Catalog
	if err := json.Unmarshal(data, &catalog); err != nil {
		return nil, fmt.Errorf("read the string source: %w", err)
	}
	if len(catalog) == 0 {
		return nil, fmt.Errorf("the string source holds no string")
	}
	languages := catalog.Languages()
	for _, name := range slices.Sorted(maps.Keys(catalog)) {
		texts := catalog[name]
		if !namePattern.MatchString(name) {
			return nil, fmt.Errorf("%q is not a resource name", name)
		}
		if !slices.Equal(slices.Sorted(maps.Keys(texts)), slices.Sorted(slices.Values(languages))) {
			return nil, fmt.Errorf("%s is not in every language: %v", name, languages)
		}
		formats := slices.Sorted(slices.Values(formatPattern.FindAllString(texts[source], -1)))
		for language, text := range texts {
			if !languagePattern.MatchString(language) {
				return nil, fmt.Errorf("%s: %q is not a language", name, language)
			}
			if text == "" || strings.TrimSpace(text) != text {
				return nil, fmt.Errorf("%s in %s is empty or starts or ends with a space", name, language)
			}
			if !slices.Equal(slices.Sorted(slices.Values(formatPattern.FindAllString(text, -1))), formats) {
				return nil, fmt.Errorf("%s in %s takes other format specifiers than in English", name, language)
			}
		}
	}
	return catalog, nil
}

// Languages lists the languages of the catalog's strings, English first.
func (c Catalog) Languages() []string {
	seen := map[string]bool{source: true}
	for _, texts := range c {
		for language := range texts {
			seen[language] = true
		}
	}
	delete(seen, source)
	return append([]string{source}, slices.Sorted(maps.Keys(seen))...)
}

// Directory is the res directory a language's strings go in.
func Directory(language string) string {
	if language == source {
		return "values"
	}
	return "values-" + language
}

// Resources renders the string resource file of one language, its strings in name order.
func (c Catalog) Resources(language string) []byte {
	var out bytes.Buffer
	out.WriteString("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n")
	out.WriteString("<!-- Generated by make android-strings from the interface catalogs, as apps/mobile/strings.json names them. -->\n")
	out.WriteString("<resources>\n")
	for _, name := range slices.Sorted(maps.Keys(c)) {
		fmt.Fprintf(&out, "    <string name=\"%s\">%s</string>\n", name, escape(c[name][language]))
	}
	out.WriteString("</resources>\n")
	return out.Bytes()
}

// androidEscapes are the characters Android's resource compiler reads specially in a string.
var androidEscapes = strings.NewReplacer(`\`, `\\`, `'`, `\'`, `"`, `\"`, "\n", `\n`)

// escape encodes text for Android's resource compiler, where a leading @ or ? reads as a reference, then as XML.
func escape(text string) string {
	text = androidEscapes.Replace(text)
	if strings.HasPrefix(text, "@") || strings.HasPrefix(text, "?") {
		text = `\` + text
	}
	var out bytes.Buffer
	// Writing to a bytes.Buffer does not fail.
	_ = xml.EscapeText(&out, []byte(text))
	return out.String()
}
